trigger:
  name: On Pull Request
  identifier: on_pull_request
  enabled: true
  orgIdentifier: default
  projectIdentifier: monorepoturbochangesetpoc
  pipelineIdentifier: monorepo_pr
  source:
    type: Webhook
    spec:
      type: Github
      spec:
        type: PullRequest
        spec:
          connectorRef: account.Github_OAuth_1777260289768
          autoAbortPreviousExecutions: true
          payloadConditions:
            # Only PRs targeting main (feature branch -> main).
            - key: targetBranch
              operator: Equals
              value: main
          headerConditions: []
          repoName: FSou1/monorepo-turbo-changeset-poc
          actions:
            - Open
            - Reopen
            - Synchronize
  inputYaml: |
    pipeline:
      identifier: monorepo_pr
      properties:
        ci:
          codebase:
            build:
              type: PR
              spec:
                number: <+trigger.prNumber>
